# this is the python script for allocating heat pumps to MV loads
import numpy as np
import pandas as pd
import os
import geopandas as gpd
import json
from scipy.spatial import ConvexHull
from shapely.geometry import Polygon
from shapely.affinity import scale
from scipy.spatial import Voronoi, voronoi_plot_2d
from geovoronoi import voronoi_regions_from_coords, points_to_coords
import tqdm
import warnings
from shapely import wkt
import matplotlib.pyplot as plt
warnings.filterwarnings('ignore')

'''
   buildings_data.csv:
   EGID: id of the building
   GKODN: x coordinate
   GKODE: y coordinate
   HBLD: thermal conductance in kWh/K
   CBLD: thermal capacity in kWh/K
   PRT: rated power in kW
   GEBF: heating equivalent area
   GAREA: specific surface area
   ISHP: heat pump installation yes/no
   T_PROFILE: temperature profile
   
   gebaeude_batiment_edificio.csv:
   GEBF: heating equivalent area
   GKODE: coordination E
   GKODN: coordination N
   GASTW: number of floor per building
   GANZWHG: number of apartments per building
   GBAUJ: year of construction
   GSTAT: building status
   GAREA: specific surface area
   '''
   
   # INPUT: buildings_data.csv generated by Lorenzo
   # OUPUT: HP_allocation.csv. The file contains the following columns:
    # EGID: id of the building
    # MV_ID: id of the MV
    # MV_osmid: osmid of the MV
    # CBLD: thermal capacity in kWh/m2K
    # HBLD: thermal conductance in kWh/m2K
    # PRT: rated power
    # GEBF: heating equivalent area
    # GAREA: specific surface area

# load the data
script_path = os.path.dirname(os.path.abspath(__file__))
data_path = os.path.join(script_path, 'Buildings_data')
grid_path = 'MV/'
buildings_data = pd.read_csv(os.path.join(data_path, 'Buildings_data.csv'), sep=',', low_memory=False)


class HP():
    def __init__(self):
        self.BUFFER_DISTANCE = 3000
        self.script_path = os.path.dirname(os.path.abspath(__file__))
        self.data_path = os.path.join(self.script_path, 'Buildings_data')
        self.grid_path = 'MV/'
        self.MV_id = dict()
        self.id = str
    
    def load_building_data(self):
        try:
            print('Loading the processed building data...')
            buildings = pd.read_csv(self.data_path+'/Buildings_data_processed.csv')
            buildings['geometry'] = buildings['geometry'].apply(wkt.loads)
            buildings = gpd.GeoDataFrame(buildings, crs='EPSG:2056', geometry=buildings.geometry)
            print('Finish loading the processed building data from the csv file.')
        except:
            buildings = pd.read_csv(self.data_path+'/Buildings_data.csv')
            buildings = gpd.GeoDataFrame(buildings, crs='EPSG:2056', geometry=gpd.points_from_xy(buildings.GKODE, buildings.GKODN))
            buildings['MV_grid'] = -1
            buildings['MV_osmid'] = -1
            print('Transform the building data to the correct coordinate system.')
        return buildings

    def load_grid_data(self):
        # load mv and lv node and edge data
        MV_path = 'MV/'
        mv_node_name = self.id+"_nodes"
        mv_edge_name = self.id+"_edges"
        mv_node_gpd=gpd.read_file(MV_path+mv_node_name)
        mv_edge_gpd=gpd.read_file(MV_path+mv_edge_name)
        mv_node_gpd['osmid'] = mv_node_gpd['osmid'].astype(int)
        mv_node_gpd['consumers'] = mv_node_gpd['consumers'].astype(bool)
        mv_node_gpd['source'] = mv_node_gpd['source'].astype(bool)
        mv_node_gpd.drop(mv_node_gpd[mv_node_gpd['el_dmd']==0].index, inplace=True)
        mv_node_gpd.reset_index(drop=True, inplace=True)
        print('Finish loading grid data {}.'.format(self.id)+" ("+str(list(self.MV_id).index(self.id)+1)+"/"+str(len(self.MV_id))+")")
        return mv_node_gpd, mv_edge_gpd
    

    def create_convex_hull(self,mv_node_gpd):
        # create convex full for the grids 
        hull = ConvexHull([list(point) for point in mv_node_gpd.geometry.apply(lambda x: (x.x,x.y))])
        hull_points = [mv_node_gpd.geometry.apply(lambda x: (x.x,x.y))[i] for i in hull.vertices]
        polygon = Polygon(hull_points)
        buffered_polygon = polygon.buffer(self.BUFFER_DISTANCE)
        buffered_hull_points = np.array(buffered_polygon.exterior.coords)
        return buffered_polygon, buffered_hull_points

    def find_building_within_hull(self, building, hull):
        points_within_hull = building[(building['MV_grid'] == '-1') | (building['MV_grid'] == -1)]
        points_within_hull = points_within_hull[points_within_hull.geometry.apply(lambda x: hull.contains(x))] 
        return points_within_hull

    def building_allocation(self, buildings, show_plot=False):
        # This function do the voronoi partitioning for the nodes and allocate the buildings to the nodes
        
        mv_node_gpd, mv_edge_gpd = self.load_grid_data()
        buffered_polygon, buffered_hull_points = self.create_convex_hull(mv_node_gpd)
        points_within_hull = self.find_building_within_hull(buildings, buffered_polygon)
        points_within_hull = points_within_hull.reset_index(drop=True)
        if len(points_within_hull) == 0:
            print('No points within the hull.')
        # partition all the mv nodes
        coords = points_to_coords(mv_node_gpd.geometry)
        coords = np.append(coords, buffered_hull_points, axis=0)
        vor = Voronoi(coords)
        regions = vor.regions
        vertices = vor.vertices
        point_region = vor.point_region
        
        print('Allocating buildings to the nodes...')
        for i in tqdm.tqdm(range(len(mv_node_gpd))):
            cor = coords[i]
            region = regions[point_region[i]]
            if -1 in region:
                region.remove(-1)
            region_vertices = vertices[region]

            for j in range(len(points_within_hull)):
                bd = points_within_hull.iloc[j]
                if bd['geometry'].within(Polygon(region_vertices)):
                    points_within_hull.at[j, 'MV_osmid'] = mv_node_gpd.iloc[i]['osmid']
                    points_within_hull.at[j, 'MV_grid'] = self.id
        print('Building allocation is completed.')

        if show_plot:
            fig, ax = plt.subplots()
            mv_edge_gpd.plot(ax=ax, color='k', linewidth=1)
            voronoi_plot_2d(vor, ax=ax, show_vertices=False, point_size=3, line_colors='grey', line_width=0.5,
                        line_alpha=0.6,show_points=False)
            # if points_within_hull['MV_grid']==-1, plot it in grey, otherwise plot it in darkorange
            points_within_hull[[points_within_hull['MV_grid']=='-1'|points_within_hull['MV_grid']==-1]].plot(ax=ax, color='grey', markersize=0.5)
            points_within_hull[[points_within_hull['MV_grid']!='-1'|points_within_hull['MV_grid']!=-1]].plot(ax=ax, color='slateblue', markersize=0.5)
            mv_node_gpd.plot(ax=ax, color='lightcoral', markersize=5, zorder=5)
            plt.xlim([buffered_polygon.bounds[0]-1500, buffered_polygon.bounds[2]+1500])
            plt.ylim([buffered_polygon.bounds[1]-1500, buffered_polygon.bounds[3]+1500])
            plt.savefig(f"{self.script_path}/HP_allocation_{self.id}.png")
            plt.show()
        return points_within_hull
    
    def merge_update(buildings, building_partly):
        cols_to_merge = ['EGID', 'MV_grid', 'MV_osmid', 'geometry']
        buildings = pd.merge(buildings, building_partly[cols_to_merge], how='left', on='EGID',suffixes=('', '_updated'))
        buildings['MV_grid'] = buildings['MV_grid_updated'].combine_first(buildings['MV_grid'])
        buildings['MV_osmid'] = buildings['MV_osmid_updated'].combine_first(buildings['MV_osmid'])
        buildings['geometry'] = buildings['geometry_updated'].combine_first(buildings['geometry'])
        buildings = buildings.drop(columns=['MV_grid_updated', 'MV_osmid_updated', 'geometry_updated'])
        return buildings
        

if __name__ == "__main__":
    HP = HP()
    with open ('data_processing/list_test_id_MV.json', 'r') as f:
        HP.MV_id = json.load(f)
    buildings = HP.load_building_data()
    # subtract the MV_id with index 821
    HP.MV_id = HP.MV_id[0:821]+HP.MV_id[822:]
    for id in HP.MV_id[500:]: # from 688, 55_0
        HP.id = id
        building_partly = HP.building_allocation(buildings, show_plot=False)
        cols_to_merge = ['EGID', 'MV_grid', 'MV_osmid', 'geometry']
        buildings = pd.merge(buildings, building_partly[cols_to_merge], how='left', on='EGID',suffixes=('', '_updated'))
        buildings['MV_grid'] = buildings['MV_grid_updated'].combine_first(buildings['MV_grid'])
        buildings['MV_osmid'] = buildings['MV_osmid_updated'].combine_first(buildings['MV_osmid'])
        buildings['geometry'] = buildings['geometry_updated'].combine_first(buildings['geometry'])
        buildings = buildings.drop(columns=['MV_grid_updated', 'MV_osmid_updated', 'geometry_updated'])
        index = HP.MV_id.index(id)
        if index%100 == 0:
            buildings.to_csv(HP.data_path+'/Buildings_data_processed.csv', index=False)
            print("saving the changes of allocation to the csv file." +" ("+str(list(HP.MV_id).index(id)+1)+"/"+str(len(HP.MV_id))+")")

    buildings.to_csv(HP.data_path+'/Buildings_data_processed.csv', index=False)
    print("saving the changes of allocation to the csv file." +" ("+str(list(HP.MV_id).index(id)+1)+"/"+str(len(HP.MV_id))+")")
    
    
    



